# syntax=docker.io/docker/dockerfile:1

FROM public.ecr.aws/w2u0w5i6/base/ubuntu:jammy AS base

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://gist.githubusercontent.com/antyung/b2e0257d15525c31363172652c825b5d/raw/7d63308d20167081e98b406091f7ddd4a06699eb/install.sh | bash
