---
version: 2

registries:
  dockerhub-registry:
    type: docker-registry
    url: registry.hub.docker.com
    username: ${{secrets.DOCKERHUB_USERNAME}}
    password: ${{secrets.DOCKERHUB_PASSWORD}}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: devcontainers
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: docker
    directories:
      - "/src/images/debian/**"
      - "/src/images/golang/**"
      - "/src/images/node/**"
      - "/src/images/python/**"
      - "/src/images/ubuntu/**"
    schedule:
      interval: daily
    commit-message:
      prefix: "build"
      include: "scope"
    registries: ["dockerhub-registry"]
