---
version: 2

registries:
  dockerhub:
    type: docker-registry
    url: registry.hub.docker.com
    username: ${{secrets.DOCKERHUB_USERNAME}}
    password: ${{secrets.DOCKERHUB_PASSWORD}}

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "ci"
      include: "scope"

  - package-ecosystem: docker
    directories: 
      - "/src/images/debian-base"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    registries:
      - dockerhub

  - package-ecosystem: docker
    directories: 
      - "/src/images/ubuntu-base"
    schedule:
      interval: daily
    commit-message:
      prefix: "chore"
      include: "scope"
    registries:
      - dockerhub
