---
services:
  devcontainer-ubuntu-base:
    container_name: devcontainer-ubuntu-base
    build:
      context: .
    volumes:
      - ..:/home/vscode/ubuntu-base:cached
    user: vscode
    tty: true
