---
services:
  devcontainer-devcontainers:
    container_name: devcontainer-devcontainers
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ..:/home/vscode/devcontainers:cached
    user: vscode
    tty: true
