---
services:
  devcontainer-debian-base:
    container_name: devcontainer-debian-base
    build:
      context: .
    volumes:
      - ..:/home/vscode/debian-base:cached
    user: vscode
    tty: true
