---
name: 'build debian-base'

on:
  push:
    branches:
      - main
    paths:
      - 'src/images/debian-base/**'
  workflow_dispatch:

env:
  IMAGE: debian-base
  AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
  AWS_ROLE_ARN: ${{secrets.AWS_ROLE_ARN}}
  GH_TOKEN: ${{secrets.GH_TOKEN}}

permissions:
  id-token: write
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 'setup qemu'
        uses: docker/setup-qemu-action@v3

      - name: 'setup docker buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'configure aws credentials'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.AWS_ROLE_ARN}}
          role-session-name: aws-oidc-${{github.repository}}-${{github.run_id}}
          aws-region: ${{env.AWS_DEFAULT_REGION}}

      - name: 'login to github container registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{env.GH_TOKEN}}

      - name: 'extract version from dockerfile'
        id: extract_version
        run: |
          TAG=$(sed -n 's/^FROM .*:\([^ ]*\)\s*.*/\1/p' ./src/images/${{env.IMAGE}}/Dockerfile)
          echo "TAG=${TAG#v}" >> $GITHUB_ENV
          echo "TAG=${TAG#v}"

      - name: 'push'
        uses: docker/bake-action@v5
        with:
          targets: push
          workdir: ./src/images/${{env.IMAGE}}
