---
name: 'build python'

on:
  push:
    branches:
      - main
    paths:
      - 'src/images/python/**'
  workflow_dispatch:

env:
  IMAGE: python
  GH_TOKEN: ${{secrets.GH_TOKEN}}

permissions:
  contents: read

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: 'setup qemu'
        uses: docker/setup-qemu-action@v3

      - name: 'setup docker buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'login to github container registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{env.GH_TOKEN}}

      - name: 'extract version from dockerfile'
        id: extract_version
        run: |
          DOCKER_TAG=$(sed -n 's/^FROM .*:\([^ ]*\)\s*.*/\1/p' ./src/images/${{env.IMAGE}}/Dockerfile)
          echo "DOCKER_TAG=${DOCKER_TAG#v}" >> $GITHUB_ENV
          echo "DOCKER_TAG=${DOCKER_TAG#v}"

      - name: 'push'
        uses: docker/bake-action@v5
        with:
          targets: push
          workdir: ./src/images/${{env.IMAGE}}
